export const ARTICLE_ALL_REQUEST = "ARTICLE_ALL_REQUEST"
export const ARTICLE_ALL_SUCCESS = "ARTICLE_ALL_SUCCESS"
export const ARTICLE_ALL_FAIL = "ARTICLE_ALL_FAIL"
export const ARTICLE_ALL_CLEAR_ERRORS = "ARTICLE_ALL_CLEAR_ERRORS"

export const SINGLE_ARTICLE_REQUEST = "SINGLE_ALL_REQUEST"
export const SINGLE_ARTICLE_SUCCESS = "SINGLE_ALL_SUCCESS"
export const SINGLE_ARTICLE_FAIL = "SINGLE_ALL_FAIL"
export const SINGLE_ARTICLE_CLEAR_ERRORS = "SINGLE_ALL_CLEAR_ERRORS"
