export const All_CARRER_REQUEST = "All_CARRER_REQUEST"
export const All_CARRER_SUCCESS = "All_CARRER_SUCCESS"
export const All_CARRER_FAIL = "All_CARRER_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const CARRER_PAGE_REQUEST = "CARRER_PAGE_REQUEST"
export const CARRER_PAGE_SUCCESS = "CARRER_PAGE_SUCCESS"
export const CARRER_PAGE_FAIL = "CARRER_PAGE_FAIL"
export const CARRER_PAGE_CLEAR_ERRORS = "CARRER_PAGE_CLEAR_ERRORS"