export const COUNSELLOR_ALL_REQUEST = "COUNSELLOR_ALL_REQUEST"
export const COUNSELLOR_ALL_SUCCESS = "COUNSELLOR_ALL_SUCCESS"
export const COUNSELLOR_ALL_FAIL = "COUNSELLOR_ALL_FAIL"
export const COUNSELLOR_ALL_CLEAR_ERRORS = "COUNSELLOR_ALL_CLEAR_ERRORS"

export const SINGLE_COUNSELLOR_REQUEST = "SINGLE_COUNSELLOR_REQUEST"
export const SINGLE_COUNSELLOR_SUCCESS = "SINGLE_COUNSELLOR_SUCCESS"
export const SINGLE_COUNSELLOR_FAIL = "SINGLE_COUNSELLOR_FAIL"
export const SINGLE_COUNSELLOR_CLEAR_ERRORS = "SINGLE_COUNSELLOR_CLEAR_ERRORS"
