export const All_COUNSOLLOR_WISE_SLOT_REQUEST = "All_COUNSOLLOR_WISE_SLOT_REQUEST"
export const All_COUNSOLLOR_WISE_SLOT_SUCCESS = "All_COUNSOLLOR_WISE_SLOT_SUCCESS"
export const All_COUNSOLLOR_WISE_SLOT_FAIL = "All_COUNSOLLOR_WISE_SLOT_FAIL"
export const All_COUNSOLLOR_WISE_SLOT_CLEAR_ERRORS = "All_COUNSOLLOR_WISE_SLOT_CLEAR_ERRORS"

export const BOOK_SLOT_REQUEST = "BOOK_SLOT_REQUEST"
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS"
export const BOOK_SLOT_FAIL = "BOOK_SLOT_FAIL"
export const BOOK_SLOT_CLEAR_ERRORS = "BOOK_SLOT_CLEAR_ERRORS"