export const VIDEO_ALL_REQUEST = "VIDEO_ALL_REQUEST"
export const VIDEO_ALL_SUCCESS = "VIDEO_ALL_SUCCESS"
export const VIDEO_ALL_FAIL = "VIDEO_ALL_FAIL"
export const VIDEO_ALL_CLEAR_ERRORS = "VIDEO_ALL_CLEAR_ERRORS"


export const SINGLE_VIDEO_REQUEST = "SINGLE_VIDEO_REQUEST"
export const SINGLE_VIDEO_SUCCESS = "SINGLE_VIDEO_SUCCESS"
export const SINGLE_VIDEO_FAIL = "SINGLE_VIDEO_FAIL"
export const SINGLE_VIDEO_CLEAR_ERRORS = "SINGLE_VIDEO_CLEAR_ERRORS"

